### ISSUE TITLE
Color code new legend specs on the map.

### ISSUE THREAD

**Issue by mikefresh** [CityOfDetroit/parcel-explorer#4]

**Comment by juancatothe** [comment]
<table>
	<thead>
		<th>Land-use </th>
		<th>Standard Color</th>
	</thead>
	<tbody>
		<tr>
			<td>Residential</td>
			<td>Yellows</td>
		</tr>
		<tr>
			<td>Single-Family Residential</td>
			<td>Yellows and light Browns</td>
		</tr>
		<tr>
			<td>Duplex</td>
			<td>Dark Yellow</td>
		</tr>
		<tr>
			<td>Multi-family</td>
			<td>Dark Brown</td>
		</tr>
		<tr>
			<td>Commercial</td>
			<td>Reds</td>
		</tr>
		<tr>
			<td>Commercial Light Density</td>
			<td>Light Red and Orange</td>
		</tr>
		<tr>
			<td>Office and Commercial Uses</td>
			<td>Red</td>
		</tr>
		<tr>
			<td>Mixed Uses</td>
			<td>Purple and hatched patterns</td>
		</tr>
		<tr>
			<td>Institutional Uses</td>
			<td>Blues</td>
		</tr>
		<tr>
			<td>Open Space</td>
			<td>Green</td>
		</tr>
		<tr>
			<td>Transportation</td>
			<td>Blacks and Grays</td>
		</tr>
		<tr>
			<td>Public and Governmental Lands</td>
			<td>Pink</td>
		</tr>
		<tr>
			<td>Environmental Areas</td>
			<td>Greens and Blues</td>
		</tr>
	</tbody>
</table>

http://www.gismanual.com/style/ColorConventions.pdf
